import React from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { usePortfolio } from '../../contexts/PortfolioContext';
import { Bell, BookOpen, Bot, Compass, GraduationCap, ShieldCheck, Users } from 'lucide-react';
import type { UserRole } from '../../types';

interface NavbarProps { currentView:string; onNavigate:(view:string,extraParams?:any)=>void; }
const ROLE_META:Record<UserRole,{label:string;icon:React.ElementType}>={
  student:{label:'Học sinh',icon:GraduationCap},teacher:{label:'Giáo viên',icon:Users},peer:{label:'Bạn học phản biện',icon:Compass},researcher:{label:'Giám khảo / Nghiên cứu',icon:BookOpen},admin:{label:'Quản trị viên',icon:ShieldCheck},ai:{label:'AI',icon:Bot}
};

export const Navbar:React.FC<NavbarProps>=({currentView,onNavigate})=>{
  const {currentUser}=useAuth();
  const {autosaveStatus,lastSavedTime,feedbacks}=usePortfolio();
  const unresolvedFeedbacksCount=feedbacks.filter(feedback=>!feedback.resolved&&feedback.studentId===currentUser.id).length;
  const roleMeta=ROLE_META[currentUser.role]; const RoleIcon=roleMeta.icon;
  const navigateHome=()=>{if(currentUser.role==='teacher')return onNavigate('teacher-dashboard');if(currentUser.role==='researcher')return onNavigate('researcher-view');if(currentUser.role==='admin')return onNavigate('admin-view');if(currentUser.role==='ai')return onNavigate('ai-workspace');return onNavigate('student-dashboard');};
  return <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 shadow-sm backdrop-blur-md"><div className="mx-auto max-w-7xl px-3 sm:px-6 lg:px-8"><div className="flex h-16 items-center justify-between gap-3">
    <button type="button" className="flex min-w-0 items-center gap-2.5 text-left" onClick={navigateHome}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-indigo-600 text-white"><BookOpen className="h-5 w-5"/></span><span className="min-w-0"><span className="block truncate text-sm font-bold tracking-tight text-slate-900 sm:text-base">Học tốt Ngữ Văn</span><span className="hidden text-xs text-slate-500 sm:block">Học, viết, nhận phản hồi và theo dõi tiến bộ</span></span></button>
    <nav className="hidden items-center gap-1 md:flex">{currentUser.role==='student'&&<><button type="button" onClick={()=>onNavigate('student-dashboard')} className={`rounded-lg px-3 py-1.5 text-sm font-medium ${currentView==='student-dashboard'?'bg-sky-50 text-sky-700':'text-slate-600 hover:bg-slate-100'}`}>Nhiệm vụ</button><button type="button" onClick={()=>onNavigate('student-analytics')} className={`rounded-lg px-3 py-1.5 text-sm font-medium ${currentView==='student-analytics'?'bg-sky-50 text-sky-700':'text-slate-600 hover:bg-slate-100'}`}>Tiến bộ</button></>}{currentUser.role==='teacher'&&<button type="button" onClick={()=>onNavigate('teacher-dashboard')} className="rounded-lg bg-emerald-50 px-3 py-1.5 text-sm font-medium text-emerald-800">Bàn giáo viên</button>}{currentUser.role==='peer'&&<button type="button" onClick={()=>onNavigate('teacher-review',{isPeerMode:true})} className="rounded-lg bg-amber-50 px-3 py-1.5 text-sm font-medium text-amber-800">Phản biện</button>}{currentUser.role==='researcher'&&<button type="button" onClick={()=>onNavigate('researcher-view')} className="rounded-lg bg-purple-50 px-3 py-1.5 text-sm font-medium text-purple-800">Giám khảo</button>}{currentUser.role==='admin'&&<button type="button" onClick={()=>onNavigate('admin-view')} className="rounded-lg bg-slate-100 px-3 py-1.5 text-sm font-medium text-slate-800">Quản trị</button>}{currentUser.role==='ai'&&<button type="button" onClick={()=>onNavigate('ai-workspace')} className="rounded-lg bg-indigo-50 px-3 py-1.5 text-sm font-medium text-indigo-800">Hàng đợi AI</button>}</nav>
    <div className="flex shrink-0 items-center gap-2">{currentUser.role==='student'&&<div className="hidden items-center gap-1.5 rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs text-slate-600 lg:flex"><span className={`h-2 w-2 rounded-full ${autosaveStatus==='saving'?'bg-amber-400':autosaveStatus==='dirty'?'bg-amber-500':'bg-emerald-500'}`}/><span>{autosaveStatus==='saving'?'Đang lưu...':autosaveStatus==='dirty'?'Chưa lưu':`Đã lưu${lastSavedTime?` (${lastSavedTime})`:''}`}</span></div>}{currentUser.role==='student'&&unresolvedFeedbacksCount>0&&<button type="button" onClick={()=>onNavigate('assignment-list')} className="relative rounded-lg p-1.5 text-slate-500 hover:bg-slate-100" title="Phản hồi mới"><Bell className="h-5 w-5"/><span className="absolute right-0 top-0 flex h-4 min-w-4 items-center justify-center rounded-full bg-rose-500 px-1 text-[10px] font-bold text-white">{unresolvedFeedbacksCount}</span></button>}<div className="hidden items-center gap-2 border-l border-slate-200 pl-3 sm:flex"><RoleIcon className="h-4 w-4 text-slate-500"/><div className="max-w-40 text-right"><div className="truncate text-xs font-semibold text-slate-800">{currentUser.name}</div><div className="truncate text-[10px] text-slate-500">{roleMeta.label}</div></div></div></div>
  </div></div></header>;
};
