import { randomBytes, scryptSync, timingSafeEqual, createHmac } from "node:crypto";
let poolPromise;
async function pool(){if(!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not configured"); if(!poolPromise) poolPromise=import("pg").then(({Pool})=>new Pool({connectionString:process.env.DATABASE_URL,max:3,ssl:{rejectUnauthorized:false}})); return poolPromise;}
function passwordHash(password,salt=randomBytes(16).toString("hex")){return salt+":"+scryptSync(password,salt,64).toString("hex");}
function passwordVerify(password,stored){const [salt,hex]=stored.split(":");if(!salt||!hex)return false;const a=scryptSync(password,salt,64),b=Buffer.from(hex,"hex");return a.length===b.length&&timingSafeEqual(a,b);}
function b64(v){return Buffer.from(typeof v==="string"?v:JSON.stringify(v)).toString("base64url");}
function sign(payload){const h=b64({alg:"HS256",typ:"JWT"}),p=b64(payload),s=process.env.JWT_SECRET||"change-this-secret-before-production";return h+"."+p+"."+createHmac("sha256",s).update(h+"."+p).digest("base64url");}
function verify(t){try{const [h,p,s]=t.split("."),key=process.env.JWT_SECRET||"change-this-secret-before-production",e=createHmac("sha256",key).update(h+"."+p).digest("base64url");if(!s||s!==e)return null;const d=JSON.parse(Buffer.from(p,"base64url").toString());return d.exp<Date.now()/1000?null:d.user;}catch{return null;}}
export async function ensureSchema(){const p=await pool();await p.query("CREATE TABLE IF NOT EXISTS app_users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE NOT NULL, name text NOT NULL, role text NOT NULL CHECK (role IN ('admin','teacher','student','researcher','ai')), password_hash text NOT NULL, must_change_password boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now())");for(const [email,name,role,password] of [["admin@cvt.edu.vn","Quản trị hệ thống","admin","Admin@2026!"],["giaovien@cvt.edu.vn","Giáo viên CVT","teacher","Teacher@2026!"],["hocsinh@cvt.edu.vn","Học sinh CVT","student","Student@2026!"],["ai@cvt.edu.vn","AI","ai","AI@2026!"]])await p.query("INSERT INTO app_users(email,name,role,password_hash,must_change_password) VALUES($1,$2,$3,$4,$5) ON CONFLICT(email) DO UPDATE SET name=EXCLUDED.name, role=EXCLUDED.role",[email,name,role,passwordHash(password),role==="ai"]);}
export async function login(email,password){await ensureSchema();const p=await pool(),r=await p.query("SELECT id,email,name,role,must_change_password,password_hash FROM app_users WHERE lower(email)=lower($1)",[email]),x=r.rows[0];if(!x||!passwordVerify(password,x.password_hash))return null;const user={id:x.id,email:x.email,name:x.name,role:x.role,mustChangePassword:x.must_change_password},now=Math.floor(Date.now()/1000);return {user,token:sign({user,iat:now,exp:now+28800})};}
export async function register(email,name,password){await ensureSchema();const p=await pool(),r=await p.query("INSERT INTO app_users(email,name,role,password_hash,must_change_password) VALUES(lower($1),$2,'student',$3,false) RETURNING id,email,name,role,must_change_password",[email,name,passwordHash(password)]),x=r.rows[0],user={id:x.id,email:x.email,name:x.name,role:x.role,mustChangePassword:x.must_change_password},now=Math.floor(Date.now()/1000);return {user,token:sign({user,iat:now,exp:now+28800})};}
export function getUser(req){const a=String(req.headers?.authorization||""),c=String(req.headers?.cookie||"").match(/cvt_token=([^;]+)/)?.[1];return verify(a.startsWith("Bearer ")?a.slice(7):c||"");}
export function send(res,status,data,token){if(token)res.setHeader("Set-Cookie",`cvt_token=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=28800`);res.setHeader("Content-Type","application/json");res.status(status).json(data);}
export function body(req){return typeof req.body==="object"?req.body:JSON.parse(req.body||"{}");}
