import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Badge, Button, Input, Modal } from '../components/ui';
import type { AcademicClass, UserRole } from '../types';
import { AcademicCapIcon, ArrowPathIcon, LockClosedIcon, ServerIcon, ShieldCheckIcon, UserGroupIcon } from '@heroicons/react/24/outline';

interface AdminAuditViewProps { onNavigate:(view:string,extraParams?:any)=>void; }
type AdminUser={id:string;email:string;name:string;role:UserRole;account_status:'active'|'locked';must_change_password:boolean;created_at:string;last_login:string|null;};
const roles:UserRole[]=['student','teacher','peer','researcher','admin','ai'];
const labels:Record<UserRole,string>={student:'Học sinh',teacher:'Giáo viên',peer:'Phản biện',researcher:'Nghiên cứu',admin:'Quản trị',ai:'AI'};
const fmt=(v:string|null)=>v?new Date(v).toLocaleString('vi-VN'):'Chưa ghi nhận';

async function adminAction(payload:unknown){
  const r=await fetch('/api/admin/manage',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(payload)});
  const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.code||'Không thể cập nhật');return d;
}

export const AdminAuditView:React.FC<AdminAuditViewProps>=({onNavigate})=>{
  const [users,setUsers]=useState<AdminUser[]>([]);const [classes,setClasses]=useState<AcademicClass[]>([]);
  const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);
  const [selected,setSelected]=useState<AdminUser|null>(null);const [editRole,setEditRole]=useState<UserRole>('student');const [editStatus,setEditStatus]=useState<'active'|'locked'>('active');
  const [tempPassword,setTempPassword]=useState('');const [classCode,setClassCode]=useState('');const [className,setClassName]=useState('');const [schoolYear,setSchoolYear]=useState('2026-2027');

  const load=async()=>{setLoading(true);setError(null);try{const [u,s]=await Promise.all([fetch('/api/admin/users',{credentials:'include'}),fetch('/api/academic/snapshot',{credentials:'include'})]);const ud=await u.json(),sd=await s.json();if(!u.ok)throw new Error(ud.message||'Không thể tải tài khoản');if(!s.ok)throw new Error(sd.message||'Không thể tải dữ liệu học thuật');setUsers(ud.users||[]);setClasses(sd.snapshot?.classes||[]);}catch(e:any){setError(e.message);}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const totals=useMemo(()=>({total:users.length,students:users.filter(x=>x.role==='student').length,teachers:users.filter(x=>x.role==='teacher').length,locked:users.filter(x=>x.account_status==='locked').length,change:users.filter(x=>x.must_change_password).length}),[users]);
  const open=(u:AdminUser)=>{setSelected(u);setEditRole(u.role);setEditStatus(u.account_status||'active');setTempPassword('');setMessage(null);};
  const saveUser=async()=>{if(!selected)return;setLoading(true);try{await adminAction({action:'update_user',userId:selected.id,role:editRole,accountStatus:editStatus});setMessage('Đã cập nhật tài khoản và ghi audit.');await load();setSelected(null);}catch(e:any){setError(e.message);}finally{setLoading(false);}};
  const resetPass=async()=>{if(!selected)return;setLoading(true);try{const d=await adminAction({action:'reset_password',userId:selected.id});setTempPassword(d.temporaryPassword);setMessage('Đã tạo mật khẩu tạm. Hãy bàn giao qua kênh riêng; hệ thống không hiển thị lại sau khi đóng hộp thoại.');await load();}catch(e:any){setError(e.message);}finally{setLoading(false);}};
  const createClass=async()=>{setLoading(true);try{await adminAction({action:'create_class',code:classCode,name:className,schoolYear});setClassCode('');setClassName('');setMessage('Đã tạo/cập nhật lớp.');await load();}catch(e:any){setError(e.message);}finally{setLoading(false);}};

  return <div className="mx-auto max-w-7xl space-y-6 pb-16">
    <header className="flex flex-col gap-4 rounded-2xl bg-slate-900 p-5 text-white sm:p-6 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-slate-400"><ShieldCheckIcon className="h-4 w-4"/>QUẢN TRỊ PRODUCTION</div><h1 className="flex items-center gap-2 text-2xl font-bold sm:text-3xl"><ServerIcon className="h-7 w-7 text-indigo-400"/>Quản trị tài khoản, lớp & audit</h1><p className="mt-2 text-sm text-slate-300">Mọi dữ liệu lấy từ PostgreSQL; thay đổi tài khoản được ghi audit phía server.</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>void load()} isLoading={loading} leftIcon={<ArrowPathIcon className="h-4 w-4"/>} className="border-slate-600 text-white">Tải lại</Button><Button size="sm" variant="academic" onClick={()=>onNavigate('researcher-view')} leftIcon={<AcademicCapIcon className="h-4 w-4"/>}>Nghiên cứu</Button></div></header>
    {error&&<Alert type="error" title="Lỗi quản trị">{error}</Alert>}{message&&<Alert type="success" title="Đã cập nhật">{message}</Alert>}
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[['Tổng tài khoản',totals.total],['Học sinh',totals.students],['Giáo viên',totals.teachers],['Bị khóa',totals.locked],['Cần đổi mật khẩu',totals.change]].map(([l,v])=><div key={String(l)} className="rounded-2xl border bg-white p-4"><div className="text-xs font-semibold text-slate-500">{l}</div><div className="mt-2 text-2xl font-bold">{loading?'—':v}</div></div>)}</section>

    <section className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-bold">Tài khoản thật</h2><p className="text-xs text-slate-500">Role, trạng thái và reset mật khẩu đều ghi trực tiếp database.</p></div><Badge variant="emerald">PostgreSQL</Badge></div><div className="overflow-x-auto"><table className="min-w-full divide-y text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Người dùng</th><th className="px-4 py-3">Vai trò</th><th className="px-4 py-3">Trạng thái</th><th className="px-4 py-3">Đăng nhập</th><th className="px-4 py-3">Thao tác</th></tr></thead><tbody className="divide-y">{!loading&&users.map(u=><tr key={u.id}><td className="px-5 py-3"><b>{u.name}</b><div className="text-xs text-slate-500">{u.email}</div></td><td className="px-4 py-3"><Badge variant="indigo">{labels[u.role]}</Badge></td><td className="px-4 py-3"><Badge variant={u.account_status==='locked'?'rose':'emerald'}>{u.account_status==='locked'?'Đã khóa':'Hoạt động'}</Badge>{u.must_change_password&&<div className="mt-1 text-[11px] text-amber-700">Cần đổi mật khẩu</div>}</td><td className="px-4 py-3 text-xs">{fmt(u.last_login)}</td><td className="px-4 py-3"><Button size="sm" variant="outline" onClick={()=>open(u)}>Quản lý</Button></td></tr>)}</tbody></table></div></section>

    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><h2 className="flex items-center gap-2 font-bold"><UserGroupIcon className="h-5 w-5"/>Lớp học</h2><div className="mt-4 space-y-2">{classes.map(c=><div key={c.id} className="flex justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm"><span><b>{c.code}</b> — {c.name}</span><span className="text-slate-500">{c.student_count||0} HS</span></div>)}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Tạo / cập nhật lớp</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Input label="Mã lớp" value={classCode} onChange={e=>setClassCode(e.target.value)} placeholder="11A2"/><Input label="Năm học" value={schoolYear} onChange={e=>setSchoolYear(e.target.value)} placeholder="2026-2027"/><div className="sm:col-span-2"><Input label="Tên lớp" value={className} onChange={e=>setClassName(e.target.value)} placeholder="Lớp 11A2"/></div><Button onClick={createClass} disabled={!classCode.trim()||!className.trim()} isLoading={loading}>Lưu lớp</Button></div></div></section>

    <Modal isOpen={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?`Quản lý ${selected.name}`:'Quản lý tài khoản'} footer={<><Button variant="secondary" onClick={()=>setSelected(null)}>Đóng</Button><Button onClick={saveUser} isLoading={loading}>Lưu thay đổi</Button></>}><div className="space-y-4"><label className="block text-sm font-semibold">Vai trò<select className="mt-2 w-full rounded-xl border p-3" value={editRole} onChange={e=>setEditRole(e.target.value as UserRole)}>{roles.map(r=><option key={r} value={r}>{labels[r]}</option>)}</select></label><label className="block text-sm font-semibold">Trạng thái<select className="mt-2 w-full rounded-xl border p-3" value={editStatus} onChange={e=>setEditStatus(e.target.value as 'active'|'locked')}><option value="active">Hoạt động</option><option value="locked">Khóa</option></select></label><div className="rounded-xl border border-amber-200 bg-amber-50 p-3"><div className="flex items-center gap-2 font-bold text-amber-900"><LockClosedIcon className="h-4 w-4"/>Reset mật khẩu</div><p className="mt-1 text-xs text-amber-800">Mật khẩu tạm chỉ hiện một lần và người dùng bắt buộc đổi khi đăng nhập.</p><Button size="sm" variant="outline" className="mt-3" onClick={resetPass} isLoading={loading}>Tạo mật khẩu tạm</Button>{tempPassword&&<div className="mt-3 rounded-lg bg-white p-3 font-mono text-sm font-bold select-all">{tempPassword}</div>}</div></div></Modal>
  </div>;
};
