import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Badge, Button, Input, Modal } from '../components/ui';
import type { AcademicClass, AuditLog, UserRole } from '../types';
import { AcademicCapIcon, ArrowPathIcon, LockClosedIcon, ServerIcon, ShieldCheckIcon, UserGroupIcon } from '@heroicons/react/24/outline';

interface AdminAuditViewProps { onNavigate:(view:string,extraParams?:any)=>void; }
type AdminUser={id:string;email:string;name:string;role:UserRole;account_status:'active'|'locked';must_change_password:boolean;created_at:string;last_login:string|null;};
const roles:UserRole[]=['student','teacher','peer','researcher','admin','ai'];
const labels:Record<UserRole,string>={student:'Học sinh',teacher:'Giáo viên',peer:'Phản biện',researcher:'Nghiên cứu',admin:'Quản trị',ai:'AI'};
const fmt=(v:string|null)=>v?new Date(v).toLocaleString('vi-VN'):'Chưa ghi nhận';
async function act(payload:unknown){const r=await fetch('/api/admin/manage',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.code||'Không thể cập nhật');return d;}

export const AdminAuditView:React.FC<AdminAuditViewProps>=({onNavigate})=>{
  const [users,setUsers]=useState<AdminUser[]>([]),[classes,setClasses]=useState<AcademicClass[]>([]),[logs,setLogs]=useState<AuditLog[]>([]);
  const [loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
  const [selected,setSelected]=useState<AdminUser|null>(null),[editRole,setEditRole]=useState<UserRole>('student'),[editStatus,setEditStatus]=useState<'active'|'locked'>('active'),[tempPassword,setTempPassword]=useState('');
  const [newName,setNewName]=useState(''),[newEmail,setNewEmail]=useState(''),[newRole,setNewRole]=useState<UserRole>('student'),[newPassword,setNewPassword]=useState('');
  const [classCode,setClassCode]=useState(''),[className,setClassName]=useState(''),[schoolYear,setSchoolYear]=useState('2026-2027');
  const [memberUser,setMemberUser]=useState(''),[memberClass,setMemberClass]=useState(''),[memberRole,setMemberRole]=useState<'student'|'teacher'>('student');

  const load=async()=>{setLoading(true);setError(null);try{const [u,s]=await Promise.all([fetch('/api/admin/users',{credentials:'include'}),fetch('/api/academic/snapshot',{credentials:'include'})]);const ud=await u.json(),sd=await s.json();if(!u.ok)throw new Error(ud.message||'Không thể tải tài khoản');if(!s.ok)throw new Error(sd.message||'Không thể tải dữ liệu học thuật');const nextUsers=ud.users||[],nextClasses=sd.snapshot?.classes||[];setUsers(nextUsers);setClasses(nextClasses);setLogs(sd.snapshot?.auditLogs||[]);if(!memberUser&&nextUsers[0])setMemberUser(nextUsers[0].id);if(!memberClass&&nextClasses[0])setMemberClass(nextClasses[0].code);}catch(e:any){setError(e.message);}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const totals=useMemo(()=>({total:users.length,students:users.filter(x=>x.role==='student').length,teachers:users.filter(x=>x.role==='teacher').length,locked:users.filter(x=>x.account_status==='locked').length,change:users.filter(x=>x.must_change_password).length}),[users]);
  const open=(u:AdminUser)=>{setSelected(u);setEditRole(u.role);setEditStatus(u.account_status||'active');setTempPassword('');setMessage(null);};
  const saveUser=async()=>{if(!selected)return;setLoading(true);try{await act({action:'update_user',userId:selected.id,role:editRole,accountStatus:editStatus});setMessage('Đã cập nhật tài khoản và ghi audit.');setSelected(null);await load();}catch(e:any){setError(e.message);}finally{setLoading(false);}};
  const resetPass=async()=>{if(!selected)return;setLoading(true);try{const d=await act({action:'reset_password',userId:selected.id});setTempPassword(d.temporaryPassword);setMessage('Đã tạo mật khẩu tạm; chỉ hiển thị trong hộp thoại hiện tại.');await load();}catch(e:any){setError(e.message);}finally{setLoading(false);}};
  const createUser=async()=>{setLoading(true);setError(null);try{const d=await act({action:'create_user',name:newName,email:newEmail,role:newRole});setNewPassword(d.temporaryPassword);setMessage('Đã tạo tài khoản thật. Sao chép mật khẩu tạm và bàn giao riêng cho người dùng.');setNewName('');setNewEmail('');await load();}catch(e:any){setError(e.message);}finally{setLoading(false);}};
  const createClass=async()=>{setLoading(true);try{await act({action:'create_class',code:classCode,name:className,schoolYear});setClassCode('');setClassName('');setMessage('Đã tạo/cập nhật lớp.');await load();}catch(e:any){setError(e.message);}finally{setLoading(false);}};
  const assignMember=async()=>{setLoading(true);try{await act({action:'assign_member',classCode:memberClass,userId:memberUser,memberRole});setMessage('Đã gán thành viên vào lớp và tạo portfolio cho các nhiệm vụ đang mở nếu là học sinh.');await load();}catch(e:any){setError(e.message);}finally{setLoading(false);}};

  return <div className="mx-auto max-w-7xl space-y-6 pb-16">
    <header className="flex flex-col gap-4 rounded-2xl bg-slate-900 p-5 text-white sm:p-6 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-slate-400"><ShieldCheckIcon className="h-4 w-4"/>QUẢN TRỊ PRODUCTION</div><h1 className="flex items-center gap-2 text-2xl font-bold sm:text-3xl"><ServerIcon className="h-7 w-7 text-indigo-400"/>Tài khoản • Lớp • Audit</h1><p className="mt-2 text-sm text-slate-300">Mọi thao tác ghi trực tiếp PostgreSQL và các thay đổi nhạy cảm được ghi audit phía server.</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>void load()} isLoading={loading} leftIcon={<ArrowPathIcon className="h-4 w-4"/>} className="border-slate-600 text-white">Tải lại</Button><Button size="sm" variant="academic" onClick={()=>onNavigate('researcher-view')} leftIcon={<AcademicCapIcon className="h-4 w-4"/>}>Nghiên cứu</Button></div></header>
    {error&&<Alert type="error" title="Lỗi quản trị">{error}</Alert>}{message&&<Alert type="success" title="Đã cập nhật">{message}</Alert>}
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[['Tổng tài khoản',totals.total],['Học sinh',totals.students],['Giáo viên',totals.teachers],['Bị khóa',totals.locked],['Cần đổi mật khẩu',totals.change]].map(([l,v])=><div key={String(l)} className="rounded-2xl border bg-white p-4"><div className="text-xs font-semibold text-slate-500">{l}</div><div className="mt-2 text-2xl font-bold">{loading?'—':v}</div></div>)}</section>

    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Tạo tài khoản</h2><p className="mt-1 text-xs text-slate-500">Tạo HS/GV/AI/Admin thật; mật khẩu tạm bắt buộc đổi lần đầu.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Input label="Họ tên" value={newName} onChange={e=>setNewName(e.target.value)}/><Input label="Email" type="email" value={newEmail} onChange={e=>setNewEmail(e.target.value)}/><label className="text-sm font-semibold">Vai trò<select className="mt-2 w-full rounded-xl border p-3" value={newRole} onChange={e=>setNewRole(e.target.value as UserRole)}>{roles.map(r=><option key={r} value={r}>{labels[r]}</option>)}</select></label><div className="flex items-end"><Button onClick={createUser} disabled={!newName.trim()||!newEmail.includes('@')} isLoading={loading}>Tạo tài khoản</Button></div></div>{newPassword&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3"><div className="text-xs font-bold text-amber-900">Mật khẩu tạm — chỉ hiển thị phiên này</div><div className="mt-2 select-all rounded-lg bg-white p-3 font-mono font-bold">{newPassword}</div></div>}</div>
      <div className="rounded-2xl border bg-white p-5"><h2 className="flex items-center gap-2 font-bold"><UserGroupIcon className="h-5 w-5"/>Tạo lớp & gán thành viên</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Input label="Mã lớp" value={classCode} onChange={e=>setClassCode(e.target.value)} placeholder="11A2"/><Input label="Năm học" value={schoolYear} onChange={e=>setSchoolYear(e.target.value)}/><Input label="Tên lớp" value={className} onChange={e=>setClassName(e.target.value)} placeholder="Lớp 11A2"/><div className="flex items-end"><Button onClick={createClass} disabled={!classCode.trim()||!className.trim()}>Lưu lớp</Button></div></div><div className="my-4 border-t"/><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Người dùng<select value={memberUser} onChange={e=>setMemberUser(e.target.value)} className="mt-2 w-full rounded-xl border p-3">{users.map(u=><option key={u.id} value={u.id}>{u.name} — {labels[u.role]}</option>)}</select></label><label className="text-sm font-semibold">Lớp<select value={memberClass} onChange={e=>setMemberClass(e.target.value)} className="mt-2 w-full rounded-xl border p-3">{classes.map(c=><option key={c.id} value={c.code}>{c.code} — {c.name}</option>)}</select></label><label className="text-sm font-semibold">Vai trò trong lớp<select value={memberRole} onChange={e=>setMemberRole(e.target.value as 'student'|'teacher')} className="mt-2 w-full rounded-xl border p-3"><option value="student">Học sinh</option><option value="teacher">Giáo viên</option></select></label><div className="flex items-end"><Button onClick={assignMember} disabled={!memberUser||!memberClass}>Gán vào lớp</Button></div></div></div></section>

    <section className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-bold">Tài khoản trong PostgreSQL</h2><p className="text-xs text-slate-500">Khóa/mở, role và reset mật khẩu có hiệu lực ngay.</p></div><Badge variant="emerald">LIVE</Badge></div><div className="overflow-x-auto"><table className="min-w-full divide-y text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Người dùng</th><th className="px-4 py-3">Vai trò</th><th className="px-4 py-3">Trạng thái</th><th className="px-4 py-3">Đăng nhập</th><th className="px-4 py-3">Thao tác</th></tr></thead><tbody className="divide-y">{users.map(u=><tr key={u.id}><td className="px-5 py-3"><b>{u.name}</b><div className="text-xs text-slate-500">{u.email}</div></td><td className="px-4 py-3"><Badge variant="indigo">{labels[u.role]}</Badge></td><td className="px-4 py-3"><Badge variant={u.account_status==='locked'?'rose':'emerald'}>{u.account_status==='locked'?'Khóa':'Hoạt động'}</Badge>{u.must_change_password&&<div className="mt-1 text-[11px] text-amber-700">Cần đổi mật khẩu</div>}</td><td className="px-4 py-3 text-xs">{fmt(u.last_login)}</td><td className="px-4 py-3"><Button size="sm" variant="outline" onClick={()=>open(u)}>Quản lý</Button></td></tr>)}</tbody></table></div></section>

    <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Audit log thật</h2><p className="mt-1 text-xs text-slate-500">200 sự kiện gần nhất từ server.</p><div className="mt-4 max-h-96 overflow-y-auto divide-y">{logs.slice(0,200).map(log=><div key={log.id} className="grid gap-1 py-3 text-xs sm:grid-cols-[170px_180px_1fr]"><span className="text-slate-500">{new Date(log.timestamp).toLocaleString('vi-VN')}</span><span className="font-semibold">{log.actorName} [{log.actorRole}]</span><span><b>{log.action}</b> <span className="text-slate-500">{log.target}</span></span></div>)}{logs.length===0&&<p className="py-6 text-sm text-slate-500">Chưa có sự kiện audit.</p>}</div></section>

    <Modal isOpen={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?`Quản lý ${selected.name}`:'Quản lý tài khoản'} footer={<><Button variant="secondary" onClick={()=>setSelected(null)}>Đóng</Button><Button onClick={saveUser} isLoading={loading}>Lưu thay đổi</Button></>}><div className="space-y-4"><label className="block text-sm font-semibold">Vai trò<select className="mt-2 w-full rounded-xl border p-3" value={editRole} onChange={e=>setEditRole(e.target.value as UserRole)}>{roles.map(r=><option key={r} value={r}>{labels[r]}</option>)}</select></label><label className="block text-sm font-semibold">Trạng thái<select className="mt-2 w-full rounded-xl border p-3" value={editStatus} onChange={e=>setEditStatus(e.target.value as 'active'|'locked')}><option value="active">Hoạt động</option><option value="locked">Khóa</option></select></label><div className="rounded-xl border border-amber-200 bg-amber-50 p-3"><div className="flex items-center gap-2 font-bold text-amber-900"><LockClosedIcon className="h-4 w-4"/>Reset mật khẩu</div><Button size="sm" variant="outline" className="mt-3" onClick={resetPass} isLoading={loading}>Tạo mật khẩu tạm</Button>{tempPassword&&<div className="mt-3 select-all rounded-lg bg-white p-3 font-mono text-sm font-bold">{tempPassword}</div>}</div></div></Modal>
  </div>;
};
