import React, { useMemo, useState } from 'react';
import { usePortfolio } from '../contexts/PortfolioContext';
import { Alert, Badge, Button, Card, FilterBar, Input, Modal } from '../components/ui';
import { ArrowLeftIcon, BookOpenIcon, PlusIcon } from '@heroicons/react/24/outline';

interface LiteratureTextsViewProps { onNavigate:(view:string,extraParams?:any)=>void; }
async function saveCatalog(payload:unknown){const r=await fetch('/api/academic/catalog',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.code||'Không thể lưu');return d;}

export const LiteratureTextsView:React.FC<LiteratureTextsViewProps>=({onNavigate})=>{
  const {literatureTexts,refreshAcademicData,isLoading}=usePortfolio();
  const [search,setSearch]=useState('');const [open,setOpen]=useState(false);const [selected,setSelected]=useState<(typeof literatureTexts)[number]|null>(null);const [error,setError]=useState<string|null>(null);
  const [title,setTitle]=useState('');const [author,setAuthor]=useState('');const [year,setYear]=useState('');const [genre,setGenre]=useState('Truyện ngắn hiện đại');const [synopsis,setSynopsis]=useState('');const [excerpt,setExcerpt]=useState('');const [context,setContext]=useState('');
  const filtered=useMemo(()=>literatureTexts.filter(t=>`${t.title} ${t.author}`.toLowerCase().includes(search.toLowerCase().trim())),[literatureTexts,search]);
  const save=async()=>{setError(null);try{await saveCatalog({action:'save_literature',title,author,year,genre,synopsis,excerpt,fullContent:excerpt,historicalContext:context,tags:['Ngữ văn THPT']});setOpen(false);setTitle('');setAuthor('');setSynopsis('');setExcerpt('');setContext('');await refreshAcademicData();}catch(e:any){setError(e.message);}};
  return <div className="mx-auto max-w-6xl space-y-6 pb-16">
    <header className="flex flex-col gap-4 rounded-2xl border bg-white p-5 sm:p-6 md:flex-row md:items-center md:justify-between"><div><Button size="sm" variant="ghost" onClick={()=>onNavigate('teacher-dashboard')} leftIcon={<ArrowLeftIcon className="h-4 w-4"/>}>Bàn giáo viên</Button><h1 className="mt-3 flex items-center gap-2 text-2xl font-bold"><BookOpenIcon className="h-6 w-6 text-indigo-700"/>Kho tác phẩm PostgreSQL</h1><p className="mt-2 text-sm text-slate-500">Ngữ liệu được lưu server-side và dùng chung cho nhiệm vụ của giáo viên.</p></div><Button onClick={()=>setOpen(true)} leftIcon={<PlusIcon className="h-4 w-4"/>}>Thêm tác phẩm</Button></header>
    {error&&<Alert type="error" title="Không thể lưu">{error}</Alert>}
    <Card padding="lg"><FilterBar searchQuery={search} onSearchChange={setSearch} searchPlaceholder="Tìm tác phẩm hoặc tác giả..." onResetFilters={()=>setSearch('')} /><div className="mt-4 grid gap-4 md:grid-cols-2">{filtered.map(t=><button key={t.id} onClick={()=>setSelected(t)} className="rounded-2xl border p-4 text-left transition hover:border-indigo-300 hover:bg-indigo-50/30"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-slate-900">{t.title}</h2><p className="text-sm text-slate-500">{t.author} • {t.year||'Không rõ năm'}</p></div><Badge variant="blue">{t.genre||'Văn học'}</Badge></div><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{t.synopsis||t.excerpt}</p></button>)}{!isLoading&&filtered.length===0&&<p className="text-sm text-slate-500">Chưa có tác phẩm phù hợp.</p>}</div></Card>
    <Modal isOpen={open} onClose={()=>setOpen(false)} title="Thêm ngữ liệu văn học" footer={<><Button variant="secondary" onClick={()=>setOpen(false)}>Hủy</Button><Button onClick={save} disabled={!title.trim()||!author.trim()}>Lưu PostgreSQL</Button></>}><div className="grid gap-3 sm:grid-cols-2"><Input label="Tác phẩm" value={title} onChange={e=>setTitle(e.target.value)}/><Input label="Tác giả" value={author} onChange={e=>setAuthor(e.target.value)}/><Input label="Năm / giai đoạn" value={year} onChange={e=>setYear(e.target.value)}/><Input label="Thể loại" value={genre} onChange={e=>setGenre(e.target.value)}/><label className="sm:col-span-2 text-sm font-semibold">Tóm tắt<textarea className="mt-2 w-full rounded-xl border p-3" rows={4} value={synopsis} onChange={e=>setSynopsis(e.target.value)}/></label><label className="sm:col-span-2 text-sm font-semibold">Trích đoạn<textarea className="mt-2 w-full rounded-xl border p-3" rows={6} value={excerpt} onChange={e=>setExcerpt(e.target.value)}/></label><label className="sm:col-span-2 text-sm font-semibold">Bối cảnh<textarea className="mt-2 w-full rounded-xl border p-3" rows={3} value={context} onChange={e=>setContext(e.target.value)}/></label></div></Modal>
    <Modal isOpen={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.title||'Chi tiết tác phẩm'} footer={<Button onClick={()=>setSelected(null)}>Đóng</Button>}>{selected&&<div className="space-y-4 text-sm leading-6"><div><b>Tác giả:</b> {selected.author}</div><div><b>Thể loại:</b> {selected.genre}</div><div><b>Tóm tắt:</b><p className="mt-1 text-slate-600">{selected.synopsis}</p></div><div><b>Trích đoạn:</b><p className="mt-1 whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-slate-700">{selected.excerpt}</p></div><div><b>Bối cảnh:</b><p className="mt-1 text-slate-600">{selected.historicalContext}</p></div></div>}</Modal>
  </div>;
};
